### PR TITLE
Add Parcels 2.2 presentation as web-exported presentation

### PR DESCRIPTION
**Pull request by CKehl**
Hi guys,

So, I wanted to also add a presentation next to the 1-slide thing. Well, EGU only allows a video (no can-do now) or a website reference. So, I exported the LibreOffice presenattion as a website.

Where to host it ? well I can host it on my personal site, but given it is about Parcels 2.2, this space seems best.

Please review and accept before Thursday evening.

### CODE REVIEW

**Review by erikvansebille — COMMENTED** [review]
I just went through, and it looks ok. Just one minor comment:
 -slides 10, 11 12, and 13 are the same except for the different mesh-gridding on the image? Really hard to spot these differences

**Review by daanreijnders — APPROVED** [review]
I think it looks fine, but could you change my name to Reijnders, D. (or simply D. Reijnders and have initials always up front)?

**Comment by reint-fischer** [comment]
Good idea!
Some small comments and ideas:

1. On img2, I like the statement "More than just particle advection". My first two thoughts for this would be:
    - modelling particle behaviour in code snippets (sinking, random walks)
    - sampling physical and biochemical quantities along trajectories
 
 those are essentially points 5 and 1 in your slide respectively. I thought, maybe just put those general ideas at the top since 2, 3 and 4 are a bit more specific.

2. For the notebook slides, I have a few ideas for additions:
    - point 1 to point 2: remove "open tutorial" and insert behind point 1 "Simulation structure notebook" to make clear what they are 'clicking' on. 
    - at point 5 maybe add that those are "simple simulations to start running".
    - Would it be an idea to add a link to the html: https://oceanparcels.org/#tutorials ?
3. A more general idea, which we could implement here if it is easy to set up. Based on [a question on one of our twitterposts](https://twitter.com/mathewbasil_/status/1387074665617657856) - would it be a good idea to share some (links to) parcels output netcdf files? Maybe we already have some from published papers? @erikvansebille? I looked for them on Yoda, but that requires access. The idea is that people might want to see some example data before downloading and running the examples. Also, some people could do research focussing only on analysis.

For any of these points I am willing to implement them myself if you share the template/LibreOffice presentation. For the html links I could add them myself.

Excited for the presentation to attract new users to the community!

**Comment by CKehl** [comment]
> I just went through, and it looks ok. Just one minor comment:
> -slides 10, 11 12, and 13 are the same except for the different mesh-gridding on the image? Really hard to spot these differences

good feedback - perhaps I can span the mesh-grid images still a bit bigger

**Comment by CKehl** [comment]
> I think it looks fine, but could you change my name to Reijnders, D. (or simply D. Reijnders and have initials always up front)?

yes, indeed, that change I did on the 1-slide thingy and the poster, but forgot it here. Will be done.

**Comment by CKehl** [comment]
> Good idea!
> Some small comments and ideas:
> 
>     1. On img2, I like the statement "More than just particle advection". My first two thoughts for this would be:
>        
>        * modelling particle behaviour in code snippets (sinking, random walks)
>        * sampling physical and biochemical quantities along trajectories
> 
> 
> those are essentially points 5 and 1 in your slide respectively. I thought, maybe just put those general ideas at the top since 2, 3 and 4 are a bit more specific.
> 
>     1. For the notebook slides, I have a few ideas for additions:
>        
>        * point 1 to point 2: remove "open tutorial" and insert behind point 1 "Simulation structure notebook" to make clear what they are 'clicking' on.
>        * at point 5 maybe add that those are "simple simulations to start running".
>        * Would it be an idea to add a link to the html: https://oceanparcels.org/#tutorials ?
> 
>     2. A more general idea, which we could implement here if it is easy to set up. Based on [a question on one of our twitterposts](https://twitter.com/mathewbasil_/status/1387074665617657856) - would it be a good idea to share some (links to) parcels output netcdf files? Maybe we already have some from published papers? @erikvansebille? I looked for them on Yoda, but that requires access. The idea is that people might want to see some example data before downloading and running the examples. Also, some people could do research focussing only on analysis.
> 
> 
> For any of these points I am willing to implement them myself if you share the template/LibreOffice presentation. For the html links I could add them myself.
> 
> Excited for the presentation to attract new users to the community!

The smaller things I take into the presentation - the other ones I just share the presentation then with you to do the things. My afternoon today is quite packed with EGU (e.g. the visualisation session).

**Comment by CKehl** [comment]
new version uploaded

**Pull request merged**
